import { db } from '../index.js'
import { triggers } from '../schema/alerts.js'
import { eq, and } from 'drizzle-orm'

const UNIVERSAL_TRIGGERS = [
  // ── SECURITY & SAFETY ──────────────────────────────────────────────────────
  {
    name: 'Panic Button',
    triggerType: 'panic_button',
    severity: 'red_alert',
    conditions: {},
    unitType: 'both',
    source: 'device',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: 0,
  },
  {
    name: 'Crash Detection',
    triggerType: 'crash_detection',
    severity: 'red_alert',
    conditions: {},
    unitType: 'vehicle',
    source: 'device',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: 0,
  },
  {
    name: 'Rollover Detection',
    triggerType: 'rollover_detection',
    severity: 'red_alert',
    conditions: {},
    unitType: 'vehicle',
    source: 'device',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: 0,
  },
  {
    name: 'Duress Code',
    triggerType: 'duress_code',
    severity: 'red_alert',
    conditions: {},
    unitType: 'principal',
    source: 'device',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: 0,
  },
  {
    name: 'GPS Jamming',
    triggerType: 'gps_jamming',
    severity: 'red_alert',
    conditions: {},
    unitType: 'both',
    source: 'device',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: 0,
  },
  {
    name: 'Device Tampered',
    triggerType: 'device_tampered',
    severity: 'red_alert',
    conditions: {},
    unitType: 'vehicle',
    source: 'device',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: 300,
  },
  {
    name: 'Fall Detection',
    triggerType: 'fall_detection',
    severity: 'red_alert',
    conditions: {},
    unitType: 'principal',
    source: 'device',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: 0,
  },

  // ── LOCATION & MOVEMENT ────────────────────────────────────────────────────
  {
    name: 'Red Zone Entry',
    triggerType: 'red_zone_entry',
    severity: 'warning',
    conditions: {},
    unitType: 'both',
    source: 'server',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: 900,
  },
  {
    name: 'Motionless — Warning',
    triggerType: 'motionless',
    severity: 'warning',
    conditions: { duration_seconds: 600 },
    unitType: 'both',
    source: 'server',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: 900,
  },
  {
    name: 'Motionless — Red Alert',
    triggerType: 'motionless',
    severity: 'red_alert',
    conditions: { duration_seconds: 1800 },
    unitType: 'both',
    source: 'server',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: 300,
  },
  {
    name: 'Device Offline — Warning',
    triggerType: 'device_offline',
    severity: 'warning',
    conditions: { duration_seconds: 900 },
    unitType: 'both',
    source: 'server',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: 900,
  },
  {
    name: 'Device Offline — Red Alert',
    triggerType: 'device_offline',
    severity: 'red_alert',
    conditions: { duration_seconds: 3600 },
    unitType: 'both',
    source: 'server',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: 300,
  },
  {
    name: 'Unauthorized Movement',
    triggerType: 'unauthorized_movement',
    severity: 'warning',
    conditions: {},
    unitType: 'vehicle',
    source: 'server',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: 900,
  },
  {
    name: 'Ignition Outside Hours',
    triggerType: 'ignition_outside_hours',
    severity: 'warning',
    conditions: {},
    unitType: 'vehicle',
    source: 'server',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: 900,
  },

  // ── DRIVER BEHAVIOR ────────────────────────────────────────────────────────
  {
    name: 'Speed — Warning',
    triggerType: 'speed',
    severity: 'warning',
    conditions: { operator: '>', value: 65, unit: 'kmh' },
    unitType: 'vehicle',
    source: 'server',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: 900,
  },
  {
    name: 'Speed — Red Alert',
    triggerType: 'speed',
    severity: 'red_alert',
    conditions: { operator: '>', value: 80, unit: 'kmh' },
    unitType: 'vehicle',
    source: 'server',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: 300,
  },
  {
    name: 'Harsh Braking',
    triggerType: 'harsh_braking',
    severity: 'warning',
    conditions: { operator: '>', value: 0.4, unit: 'g' },
    unitType: 'vehicle',
    source: 'device',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: 900,
  },
  {
    name: 'Harsh Acceleration',
    triggerType: 'harsh_acceleration',
    severity: 'warning',
    conditions: { operator: '>', value: 0.4, unit: 'g' },
    unitType: 'vehicle',
    source: 'device',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: 900,
  },
  {
    name: 'Sharp Cornering',
    triggerType: 'sharp_cornering',
    severity: 'warning',
    conditions: { operator: '>', value: 0.4, unit: 'g' },
    unitType: 'vehicle',
    source: 'device',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: 900,
  },
  {
    name: 'Idle Engine — Advisory',
    triggerType: 'idle_engine',
    severity: 'advisory',
    conditions: { duration_seconds: 600 },
    unitType: 'vehicle',
    source: 'server',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: 3600,
  },
  {
    name: 'Idle Engine — Warning',
    triggerType: 'idle_engine',
    severity: 'warning',
    conditions: { duration_seconds: 1800 },
    unitType: 'vehicle',
    source: 'server',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: 1800,
  },

  // ── VEHICLE HEALTH ─────────────────────────────────────────────────────────
  {
    name: 'Loss of Power',
    triggerType: 'loss_of_power',
    severity: 'red_alert',
    conditions: {},
    unitType: 'vehicle',
    source: 'device',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: 0,
  },
  {
    name: 'Fuel — Warning',
    triggerType: 'fuel',
    severity: 'warning',
    conditions: { operator: '<', value: 10, unit: 'percent' },
    unitType: 'vehicle',
    source: 'device',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: 900,
  },
  {
    name: 'Fuel — Critical',
    triggerType: 'fuel',
    severity: 'red_alert',
    conditions: { operator: '<', value: 5, unit: 'percent' },
    unitType: 'vehicle',
    source: 'device',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: 300,
  },
  {
    name: 'Low Tire Pressure',
    triggerType: 'low_tire_pressure',
    severity: 'warning',
    conditions: {},
    unitType: 'vehicle',
    source: 'device',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: 900,
  },
  {
    name: 'Check Engine',
    triggerType: 'check_engine',
    severity: 'warning',
    conditions: {},
    unitType: 'vehicle',
    source: 'device',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: 3600,
  },
  {
    name: 'Engine Temp — Warning',
    triggerType: 'engine_temp',
    severity: 'warning',
    conditions: { operator: '>', value: 105, unit: 'celsius' },
    unitType: 'vehicle',
    source: 'device',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: 900,
  },
  {
    name: 'Engine Temp — Critical',
    triggerType: 'engine_temp',
    severity: 'red_alert',
    conditions: { operator: '>', value: 115, unit: 'celsius' },
    unitType: 'vehicle',
    source: 'device',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: 300,
  },
  {
    name: 'Cabin Temp Out of Range',
    triggerType: 'cabin_temp',
    severity: 'warning',
    conditions: { min: 16, max: 28, unit: 'celsius' },
    unitType: 'vehicle',
    source: 'device',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: 900,
  },
  {
    name: 'Door Open While Moving',
    triggerType: 'door_open_moving',
    severity: 'warning',
    conditions: { min_speed_kmh: 5 },
    unitType: 'vehicle',
    source: 'device',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: 900,
  },
  {
    name: 'Maintenance Due',
    triggerType: 'maintenance_due',
    severity: 'advisory',
    conditions: { interval_km: 5000 },
    unitType: 'vehicle',
    source: 'server',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: null,
  },
  {
    name: 'Tracker Battery — Warning',
    triggerType: 'tracker_battery',
    severity: 'warning',
    conditions: { operator: '<', value: 20, unit: 'percent' },
    unitType: 'both',
    source: 'device',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: 3600,
  },
  {
    name: 'Tracker Battery — Critical',
    triggerType: 'tracker_battery',
    severity: 'red_alert',
    conditions: { operator: '<', value: 5, unit: 'percent' },
    unitType: 'both',
    source: 'device',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: 900,
  },

  // ── BIOMETRICS (principal only) ────────────────────────────────────────────
  {
    name: 'Heart Rate High — Warning',
    triggerType: 'heart_rate',
    severity: 'warning',
    conditions: { operator: '>', value: 100, unit: 'bpm', sustained_seconds: 60 },
    unitType: 'principal',
    source: 'device',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: 900,
  },
  {
    name: 'Heart Rate High — Critical',
    triggerType: 'heart_rate',
    severity: 'red_alert',
    conditions: { operator: '>', value: 120, unit: 'bpm', sustained_seconds: 30 },
    unitType: 'principal',
    source: 'device',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: 300,
  },
  {
    name: 'Heart Rate Low — Warning',
    triggerType: 'heart_rate',
    severity: 'warning',
    conditions: { operator: '<', value: 45, unit: 'bpm', sustained_seconds: 60 },
    unitType: 'principal',
    source: 'device',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: 900,
  },
  {
    name: 'Heart Rate Low — Critical',
    triggerType: 'heart_rate',
    severity: 'red_alert',
    conditions: { operator: '<', value: 35, unit: 'bpm', sustained_seconds: 30 },
    unitType: 'principal',
    source: 'device',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: 300,
  },
  {
    name: 'Blood Pressure High — Warning',
    triggerType: 'blood_pressure',
    severity: 'warning',
    conditions: { operator: '>', value: 140, measure: 'systolic', unit: 'mmhg' },
    unitType: 'principal',
    source: 'device',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: 900,
  },
  {
    name: 'Blood Pressure High — Critical',
    triggerType: 'blood_pressure',
    severity: 'red_alert',
    conditions: { operator: '>', value: 180, measure: 'systolic', unit: 'mmhg' },
    unitType: 'principal',
    source: 'device',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: 300,
  },
  {
    name: 'Blood Pressure Low',
    triggerType: 'blood_pressure',
    severity: 'warning',
    conditions: { operator: '<', value: 90, measure: 'systolic', unit: 'mmhg' },
    unitType: 'principal',
    source: 'device',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: 900,
  },
  {
    name: 'Blood Oxygen — Warning',
    triggerType: 'blood_oxygen',
    severity: 'warning',
    conditions: { operator: '<', value: 94, unit: 'percent' },
    unitType: 'principal',
    source: 'device',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: 900,
  },
  {
    name: 'Blood Oxygen — Critical',
    triggerType: 'blood_oxygen',
    severity: 'red_alert',
    conditions: { operator: '<', value: 90, unit: 'percent' },
    unitType: 'principal',
    source: 'device',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: 300,
  },
  {
    name: 'Wearable Battery Low',
    triggerType: 'wearable_battery',
    severity: 'advisory',
    conditions: { operator: '<', value: 20, unit: 'percent' },
    unitType: 'principal',
    source: 'device',
    isUniversal: true,
    isSystem: true,
    cooldownSeconds: 3600,
  },
]

async function seed() {
  console.log('Seeding universal triggers...')
  let inserted = 0
  let skipped = 0

  for (const t of UNIVERSAL_TRIGGERS) {
    const [existing] = await db
      .select({ id: triggers.id })
      .from(triggers)
      .where(and(eq(triggers.name, t.name), eq(triggers.isSystem, true)))
      .limit(1)

    if (existing) {
      skipped++
    } else {
      await db.insert(triggers).values(t)
      inserted++
    }
  }

  console.log(`Done. ${inserted} inserted, ${skipped} already existed.`)
  process.exit(0)
}

seed().catch(err => {
  console.error(err)
  process.exit(1)
})
